tests: Code coverage for selecting certificate by serial and issuer
Signed-off-by: Jakub Jelen <jjelen@redhat.com>

diff --git a/tests/tcerts b/tests/tcerts
--- a/tests/tcerts
+++ b/tests/tcerts
@@ -24,7 +24,7 @@ if [[ ! ${DATA} =~ ${CHECK} ]]; then
     exit 1
 fi
 
-title PARA "Use storeutl command to match specific certs via params"
+title PARA "Use storeutl command to match specific certs via subject params"
 
 SUBJECTS=("/O=PKCS11 Provider/CN=My Test Cert"
           "/O=PKCS11 Provider/CN=My EC Cert"
@@ -42,6 +42,17 @@ if [[ ! ${DATA} =~ "Total found: 1" ]]; then
     exit 1
 fi
 done
+
+title PARA "Use storectl command to match certs by issuer and serial"
+ossl '
+storeutl -certs -issuer "/CN=Issuer" -serial 1
+                -out ${TMPPDIR}/storeutl-crt-ca.txt
+                pkcs11:type=cert'
+DATA=$(cat "${TMPPDIR}/storeutl-crt-ca.txt")
+if [[ ! ${DATA} =~ "Total found: 1" ]]; then
+    echo "Cert not found matching by issuer=/CN=Issuer with serial=1"
+    exit 1
+fi
 
 title PARA "Test fetching certificate without PIN in config files"
 ORIG_OPENSSL_CONF=${OPENSSL_CONF}
