Add support for RSA-PSS keys
This is not as straightforward as it looked like initially and consists of
several changes that surface on different occasions:

 * The private RSA keys in PKCS#11 can have `CKA_ALLOWED_MECHANISMS` which can
   be used to determine if a key is generic key (can be used for any operation)
   or RSA-PSS key, so that it could be used only for any or specified
   operations.

 * These keys get different identifier on OpenSSL level. They also get different
   OIDs on the ASN.1 in various places of the X.509 certificates:

   * The signatures in X.509 has a OID + parameters describing the hashes, mgf
     and salt length used to create the signature. This is mandatory.

   * The public key encoding can contain the RSA-PSS restrictions. These are not
     mandatory so it allows us to indicate the key is restricted to any PSS
     operations without the need to stick to specific combination of parameters.
     But it allows to specify only one of the parameters (hash, MGF1-hash,
     salt size). But there is no way to express this in PKCS#11. We can limit
     ourselves to specific hash. Note, from this only the diffentiation between
     RSA and RSA-PSS SPKI is done

Given that the certtool we use for signing certificates during setup can not
distinguish RSA-PSS restricted keys and therefore generates unrestricted
certificates, we need to generate the certificate later using openssl, making
the tests a bit more ugly.

Fixes: #489

Signed-off-by: Jakub Jelen <jjelen@redhat.com>

diff --git a/tests/tdemoca b/tests/tdemoca
--- a/tests/tdemoca
+++ b/tests/tdemoca
@@ -73,6 +73,54 @@ if [[ -n $ED2PRIURI ]]; then
     ca -batch -in ${DEMOCA}/cert-ed2.csr -keyfile ${PRIURI} -out ${DEMOCA}/cert.pem'
 fi
 
+if [[ -n $RSAPSSPRIURI ]]; then
+    title PARA "Generating a new CSR with existing RSA-PSS key in token"
+    ossl '
+    req -batch -noenc -new -key ${RSAPSSPRIURI} -sigopt rsa_padding_mode:pss
+        -subj "/CN=testing-rsapss-signing/O=PKCS11 Provider/C=US"
+        -sigopt rsa_padding_mode:pss
+        -out ${DEMOCA}/cert-rsa-pss.csr'
+
+    title PARA "Signing the new RSA-PSS key certificate"
+    ossl '
+    ca -batch -in ${DEMOCA}/cert-rsa-pss.csr -keyfile ${PRIURI} -out ${DEMOCA}/cert.pem'
+
+    ossl 'x509 -text -in ${DEMOCA}/cert.pem' "$helper_emit"
+    output="$helper_output"
+    FAIL=1
+    echo "$output" | grep "No PSS parameter restrictions" > /dev/null 2>&1 && FAIL=0
+    if [ $FAIL -ne 0 ]; then
+        echo "Generated certificate has some RSA-PSS restrictions while it should not"
+        echo "$output";
+        exit 1
+    fi
+fi
+
+if [[ -n $RSAPSS2PRIURI ]]; then
+    title PARA "Generating a new CSR with existing SHA256 restricted RSA-PSS key in token"
+    ossl '
+    req -batch -noenc -new -key ${RSAPSS2PRIURI} -sigopt rsa_padding_mode:pss
+        -subj "/CN=testing-rsapss-sha2-signing/O=PKCS11 Provider/C=US"
+        -out ${DEMOCA}/cert-rsa-pss2.csr
+        -sigopt rsa_padding_mode:pss
+        -sigopt digest:sha256'
+
+    title PARA "Signing the new SHA256 restricted RSA-PSS key certificate"
+    ossl '
+    ca -batch -in ${DEMOCA}/cert-rsa-pss2.csr -keyfile ${PRIURI} -out ${DEMOCA}/cert.pem'
+
+    ossl 'x509 -text -in ${DEMOCA}/cert.pem' "$helper_emit"
+    output="$helper_output"
+    # TODO we should get restrictions visible here when implemented
+    #FAIL=0
+    #echo "$output" | grep "No PSS parameter restrictions" > /dev/null 2>&1 && FAIL=1
+    #if [ $FAIL -ne 0 ]; then
+    #    echo "Generated certificate does not have any RSA-PSS restrictions while it should"
+    #    echo "$output";
+    #    exit 1
+    #fi
+fi
+
 title PARA "Set up OCSP"
 ossl '
 req -batch -noenc -new -subj "/CN=OCSP/O=PKCS11 Provider/C=US"
