tests: Properly check results of tests
 * reuse the killing property in both tests
 * run openssl commands under wrappers to check their exit codes
 * make sure children processes are terminated to avoid issues when executed
   under valgrind
 * use different port numbers in tests to minimize test dependencies

Signed-off-by: Jakub Jelen <jjelen@redhat.com>

diff --git a/tests/tdemoca b/tests/tdemoca
--- a/tests/tdemoca
+++ b/tests/tdemoca
@@ -15,22 +15,26 @@ touch ${DEMOCA}/index.txt
 
 title PARA "Generating CA cert if needed"
 if [ ! -e ${DEMOCA}/cacert.pem ]; then
-    openssl req -batch -noenc -x509 -new -key ${PRIURI} -out ${DEMOCA}/cacert.pem
+    ossl 'req -batch -noenc -x509 -new -key ${PRIURI} -out ${DEMOCA}/cacert.pem'
 fi
 
 title PARA "Generating a new CSR"
-openssl req -batch -noenc -newkey rsa:2048 \
-            -subj '/CN=testing-csr-signing/O=PKCS11 Provider/C=US' \
-            -keyout ${DEMOCA}/cert.key -out ${DEMOCA}/cert.csr
+ossl '
+req -batch -noenc -newkey rsa:2048
+    -subj "/CN=testing-csr-signing/O=PKCS11 Provider/C=US"
+    -keyout ${DEMOCA}/cert.key -out ${DEMOCA}/cert.csr'
 
 title PARA "Signing the new certificate"
-openssl ca -batch -in ${DEMOCA}/cert.csr -keyfile ${PRIURI} -out ${DEMOCA}/cert.pem
+ossl '
+ca -batch -in ${DEMOCA}/cert.csr -keyfile ${PRIURI} -out ${DEMOCA}/cert.pem'
 
 title PARA "Set up OCSP"
-openssl req -batch -noenc -new -subj '/CN=OCSP/O=PKCS11 Provider/C=US' \
-            -key ${PRIURI} -out ${DEMOCA}/ocspSigning.csr
-openssl ca -batch -keyfile ${PRIURI} -cert ${DEMOCA}/cacert.pem \
-            -in ${DEMOCA}/ocspSigning.csr -out ${DEMOCA}/ocspSigning.pem
+ossl '
+req -batch -noenc -new -subj "/CN=OCSP/O=PKCS11 Provider/C=US"
+    -key ${PRIURI} -out ${DEMOCA}/ocspSigning.csr'
+ossl '
+ca -batch -keyfile ${PRIURI} -cert ${DEMOCA}/cacert.pem
+   -in ${DEMOCA}/ocspSigning.csr -out ${DEMOCA}/ocspSigning.pem'
 
 
 #The next test is not working on Debian for some reason, so skip the rest for now
@@ -39,13 +43,35 @@ if [ -e /etc/debian_version ]; then
 fi
 
 title PARA "Run OCSP"
-trap 'jobs -p | xargs -r kill >/dev/null 2>&1' EXIT
+PORT=12345
+trap kill_children EXIT
 #Unclear why but w/o -rmd sha1 this fails
 #call this without wrapper otherwise we have issues killing it later ...
 $CHECKER openssl ocsp -index ${DEMOCA}/index.txt -rsigner \
     ${DEMOCA}/ocspSigning.pem -rkey ${PRIURI} -CA ${DEMOCA}/cacert.pem \
     -rmd sha1 -port ${PORT} -text &
 sleep 0.5
-openssl ocsp -CAfile ${DEMOCA}/cacert.pem -issuer ${DEMOCA}/cacert.pem \
-             -cert ${DEMOCA}/cert.pem -resp_text -noverify \
-             -url http://127.0.0.1:12345
+# with valgrind, it might take a bit longer
+if [ -n "$VALGRIND" ]; then
+    sleep 5
+fi
+ossl '
+ocsp -CAfile ${DEMOCA}/cacert.pem -issuer ${DEMOCA}/cacert.pem
+     -cert ${DEMOCA}/cert.pem -resp_text -noverify
+     -url http://127.0.0.1:${PORT}' $helper_emit
+output="$helper_output"
+FAIL=0
+echo $output | grep ": good" > /dev/null 2>&1 || FAIL=1
+if [ $FAIL -eq 1 ]; then
+    echo "The OCSP response failed"
+    echo
+    echo "Original command output:"
+    echo "$output"
+    echo
+    exit 1
+fi
+
+title PARA "Kill any remaining children and wait for them"
+kill_children
+
+exit 0
